struct domain_extensions {
     char *domain;
     char *country;
};

const struct domain_extensions country_codes[] =
    {{".ac", "Ascension Island"},
     {".ad", "Andorra"},
     {".ae", "United Arab Emirates"},
     {".af", "Afghanistan"},
     {".ag", "Antigua and Barbuda"},
     {".ai", "Anguilla"},
     {".al", "Albania"},
     {".am", "Armenia"},
     {".an", "Netherlands Antilles (now deleted with the 2010 political dissolution of this region as an overseas territory)"},
     {".ao", "Angola"},
     {".aq", "Antarctic"},
     {".ar", "Argentina"},
     {".as", "American Samoa"},
     {".at", "Austria"},
     {".au", "Australia"},
     {".aw", "Aruba"},
     {".ax", "Aland Islands"},
     {".az", "Azerbaijan"},
     {".ba", "Bosnia and Herzegovina"},
     {".bb", "Barbados"},
     {".bd", "Bangladesh"},
     {".be", "Belgium"},
     {".bf", "Burkina Faso"},
     {".bg", "Bulgaria"},
     {".bh", "Bahrain"},
     {".bi", "Burundi"},
     {".bj", "Benin"},
     {".bl", "Saint-Barthelemy"},
     {".bm", "Bermuda"},
     {".bn", "Brunei"},
     {".bo", "Bolivia"},
     {".br", "Brazil"},
     {".bq", "Bonaire"},
     {".bs", "Bahamas"},
     {".bt", "Bhutan"},
     {".bv", "Bouvet Island (registration not yet possible)"},
     {".bw", "Botswana"},
     {".by", "Belarus"},
     {".bz", "Belize"},
     {".ca", "Canada"},
     {".cc", "Cocos Islands"},
     {".cd", "Democratic Republic of the Congo"},
     {".cf", "Central African Republic"},
     {".cg", "Republic of the Congo"},
     {".ch", "Switzerland"},
     {".ci", "Cote d’Ivoire"},
     {".ck", "Cook Islands"},
     {".cl", "Chile"},
     {".cm", "Cameroon"},
     {".cn", "China"},
     {".co", "Colombia"},
     {".cr", "Costa Rica"},
     {".cs", "Czechoslovakia (now deleted)"},
     {".cu", "Cuba"},
     {".cv", "Cape Verde"},
     {".cw", "Curacao"},
     {".cx", "Christmas Island"},
     {".cy", "Cyprus"},
     {".cz", "Czech Republic"},
     {".dd", "German Democratic Republic (never activated)"},
     {".de", "Germany"},
     {".dj", "Djibuti"},
     {".dk", "Denmark"},
     {".dm", "Dominica"},
     {".do", "Dominican Republic"},
     {".dz", "Algeria"},
     {".ec", "Ecuador"},
     {".ee", "Estonia"},
     {".eg", "Egypt"},
     {".er", "Eritrea"},
     {".es", "Spain"},
     {".et", "Ethiopia"},
     {".eu", "European Union"},
     {".fi", "Finland"},
     {".fj", "Fiji"},
     {".fk", "Falkland Islands"},
     {".fm", "Micronesia"},
     {".fo", "Faroe"},
     {".fr", "France"},
     {".ga", "Gabon"},
     {".gb", "United Kingdom (no longer in use)"},
     {".gd", "Grenada"},
     {".ge", "Georgia"},
     {".gf", "French Guiana"},
     {".gg", "Guernsey"},
     {".gh", "Ghana"},
     {".gi", "Gibraltar"},
     {".gl", "Greenland"},
     {".gm", "Gambia"},
     {".gn", "Guinea"},
     {".gp", "Guadeloupe"},
     {".gq", "Equatorial Guinea"},
     {".gr", "Greece"},
     {".gs", "South Georgia and the South Sandwich Islands"},
     {".gt", "Guatemala"},
     {".gu", "Guam"},
     {".gw", "Guinea-Bissau"},
     {".gy", "Guyana"},
     {".hk", "Hong Kong"},
     {".hm", "Heard Island and McDonald Islands"},
     {".hn", "Honduras"},
     {".hr", "Croatia"},
     {".ht", "Haiti"},
     {".hu", "Hungary"},
     {".id", "Indonesia"},
     {".ie", "Ireland"},
     {".il", "Israel"},
     {".im", "Isle of Man"},
     {".in", "India"},
     {".io", "British Indian Ocean Territory"},
     {".iq", "Iraq"},
     {".ir", "Iran"},
     {".is", "Iceland"},
     {".it", "Italy"},
     {".je", "Jersey"},
     {".jm", "Jamaica"},
     {".jo", "Jordan"},
     {".jp", "Japan"},
     {".ke", "Kenya"},
     {".kg", "Kyrgyzstan"},
     {".kh", "Cambodia"},
     {".ki", "Kiribati"},
     {".km", "Comoros"},
     {".kn", "St. Kitts and Nevis"},
     {".kp", "North Korea"},
     {".kr", "South Korea"},
     {".kw", "Kuwait"},
     {".ky", "Cayman Islands"},
     {".kz", "Kazakhstan"},
     {".la", "Laos"},
     {".lb", "Lebanon"},
     {".lc", "St. Lucia"},
     {".li", "Liechtenstein"},
     {".lk", "Sri Lanka"},
     {".lr", "Liberia"},
     {".ls", "Lesotho"},
     {".lt", "Lithuania"},
     {".lu", "Luxembourg"},
     {".lv", "Latvia"},
     {".ly", "Libya"},
     {".ma", "Marocco"},
     {".mc", "Monaco"},
     {".md", "Moldova"},
     {".me", "Montenegro"},
     {".mf", "Saint Martin"},
     {".mg", "Madagascar"},
     {".mh", "Marshall Islands"},
     {".mk", "Macedonia"},
     {".ml", "Mali"},
     {".mm", "Myanmar"},
     {".mn", "Mongolia"},
     {".mo", "Macau"},
     {".mp", "Northern Mariana Islands"},
     {".mq", "Martinique"},
     {".mr", "Mauritania"},
     {".ms", "Montserrat"},
     {".mt", "Malta"},
     {".mu", "Mauritius"},
     {".mv", "Maldives"},
     {".mw", "Malawi"},
     {".mx", "Mexico"},
     {".my", "Malaysia"},
     {".mz", "Mozambique"},
     {".na", "Namibia"},
     {".nc", "New Caledonia"},
     {".ne", "Niger"},
     {".nf", "Norfolk Island"},
     {".ng", "Nigeria"},
     {".ni", "Nicaragua"},
     {".nl", "Netherlands"},
     {".no", "Norway"},
     {".np", "Nepal"},
     {".nr", "Nauru"},
     {".nu", "Niue"},
     {".nz", "New Zealand"},
     {".om", "Oman"},
     {".pa", "Panama"},
     {".pe", "Peru"},
     {".pf", "French Polynesia"},
     {".pg", "Papua New Guinea"},
     {".ph", "Philippines"},
     {".pk", "Pakistan"},
     {".pl", "Poland"},
     {".pm", "Saint Pierre and Miquelon"},
     {".pn", "Pitcairn Islands"},
     {".pr", "Puerto Rico"},
     {".ps", "Palestine"},
     {".pt", "Portugal"},
     {".pw", "Palau"},
     {".py", "Paraguay"},
     {".qa", "Qatar"},
     {".re", "Reunion"},
     {".ro", "Romania"},
     {".rs", "Serbia"},
     {".ru", "Russia"},
     {".rw", "Rwanda"},
     {".sa", "Saudi Arabia"},
     {".sb", "Solomon Islands"},
     {".sc", "Seychelles"},
     {".sd", "Sudan"},
     {".se", "Sweden"},
     {".sg", "Singapore"},
     {".sh", "St. Helena"},
     {".si", "Slovenia"},
     {".sj", "Svalbard and Jan Mayen (registration is not yet possible)"},
     {".sk", "Slovakia"},
     {".sl", "Sierra Leone"},
     {".sm", "San Marino"},
     {".sn", "Senegal"},
     {".so", "Somalia"},
     {".sr", "Suriname"},
     {".ss", "South Sudan"},
     {".st", "Sao Tome and Principe"},
     {".su", "Soviet Union (this TLD has been managed by Russia since the dissolution of the USSR)"},
     {".sv", "El Salvador"},
     {".sx", "Sint Maarten"},
     {".sy", "Syria"},
     {".sz", "Swaziland"},
     {".tc", "Turks and Caicos Islands"},
     {".td", "Chad"},
     {".tf", "French Southern and Antarctic Lands"},
     {".tg", "Togo"},
     {".th", "Thailand"},
     {".tj", "Tajikistan"},
     {".tk", "Tokelau"},
     {".tl", "Timor-Leste"},
     {".tm", "Turkmenistan"},
     {".tn", "Tunisia"},
     {".to", "Tonga"},
     {".tp", "Timor-Leste (now deleted)"},
     {".tr", "Turkey, Turkish Republic of Northern Cyprus"},
     {".tt", "Trinidad and Tobago"},
     {".tv", "Tuvalu"},
     {".tw", "Taiwan"},
     {".tz", "Tanzania"},
     {".ua", "Ukraine"},
     {".ug", "Uganda"},
     {".uk", "United Kingdom"},
     {".um", "United States Minor Outlying Islands (now deleted)"},
     {".us", "United States"},
     {".uy", "Uruguay"},
     {".uz", "Uzbekistan"},
     {".va", "Vatican City"},
     {".vc", "St. Vincent and the Grenadines"},
     {".ve", "Venezuela"},
     {".vg", "Britische Virgin Islands"},
     {".vi", "United States Virgin Islands"},
     {".vn", "Vietnam"},
     {".vu", "Vanuatu"},
     {".wf", "Wallis and Futuna (also .fr)"},
     {".ws", "Samoa"},
     {".ye", "Yemen"},
     {".yt", "Mayotte (French region, also .fr"},
     {".yu", "Yugoslavia (now deleted, after the dissolution of the former Yugoslavia the TLD was used by Serbia and Montenegro until 2010)"},
     {".za", "South Africa"},
     {".zm", "Zambia"},
     {".zr", "Zaire (now deleted, since the country was renamed in 1997)"},
     {".zw", "Zimbabwe"}};